create database mycatalog;

create table item (
id int generated always as identity,
publish_date date,
archived boolean,
constraint pk_id primary key(id));

create table author(
id int generated always as identity,
first_name varchar(300),
last_name varchar(300),
constraint pk_authorid primary key(id)
);

create table game(
id int generated always as identity,
author_id int,
item_id int,
multiplayer boolean,
last_play_at date,
publish_date date,
constraint pk_game_id primary key(id),
constraint fk_item_id foreign key (item_id) references item(id),
constraint fk_author_id foreign key (author_id) references author(id)
);

-- Create Genre Table\
CREATE TABLE
  genre (
    id int GENERATED BY DEFAULT AS IDENTITY,
    name varchar(250),
    CONSTRAINT genre_pk PRIMARY KEY (id)
  );


CREATE TABLE
  musicalbum (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publish_date date,
    archived boolean,
    on_spotify boolean,
    genre_id int CONSTRAINT genre_fkey FOREIGN KEY (genre_id) REFERENCES genre(id),
  );

  CREATE TABLE labels ( 
  id SERIAL PRIMARY KEY,
  title VARCHAR(255),
  color VARCHAR(255),
  published_date DATE,
  item_id INT,
  items text[],
  FOREIGN KEY (item_id) REFERENCES items(id)
);

CREATE TABLE books (
    id SERIAL PRIMARY KEY,
    item_id INT,
    title VARCHAR(255),
    author_id INT,
    label_id Int,
    cover_state VARCHAR(255),
    publisher VARCHAR(255),
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (label_id) REFERENCES labels(id),
    FOREIGN KEY (author_id) REFERENCES authors(id)
);